version: '3.6'

services:
  discord-oauth2-server:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    command: sh
    ports:
      - "8085:8085"
    volumes:
      - .:/app/
    external_links:
      - core-db
    labels:
      traefik.enable: true
      traefik.backend: discord_oauth2_server
      traefik.frontend.rule: HostRegexp:discord-oauth.fearthec.test
      traefik.frontend.priority: 1
      traefik.docker.network: traefik
      traefik.port: 8085
    networks:
      ftcbot_dev:

networks:
  ftcbot_dev:
    external: true
  traefik:
    external: true
